In [1]:
from engine import Tensor
import numpy as np
import nn

In [18]:
Tensor.randint(1, 2,(2, 2)).pad(1)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]

In [8]:
## Does it work in simple contexts?

xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [[1.0], 
      [-1.0], 
      [-1.0], 
      [1.0]]



net = nn.MLP()

x = Tensor(xs)
y_real = Tensor(ys)

for k in range(10000):
    net.zero_grad()
    y_pred = net(x)
#     loss = ((y_pred - y_real)**2).sum() / y_real.shape[0]
    loss = ((y_pred - y_real)**2).mean(0)
#     loss = loss_fn(y_pred, y_real)
    loss.backward()
    
    for p in net.parameters():
        if p.grad is not None:
            p.data -= 0.005 * p.grad  # Apply the learning rate.
    
    if k % 200 == 0:
        print(k, loss.data)
    
y_pred

0 [0.59198743]
200 [0.01661191]
400 [0.00627089]
600 [0.00360411]
800 [0.00241379]
1000 [0.00172821]
1200 [0.00128797]
1400 [0.00098778]
1600 [0.00077437]
1800 [0.00061779]
2000 [0.00049994]
2200 [0.00040937]
2400 [0.00033856]
2600 [0.00028237]
2800 [0.00023722]
3000 [0.00020056]
3200 [0.00017049]
3400 [0.00014564]
3600 [0.00012495]
3800 [0.00010762]
4000 [9.300519e-05]
4200 [8.062777e-05]
4400 [7.0087044e-05]
4600 [6.1082064e-05]
4800 [5.3355707e-05]
5000 [4.6706446e-05]
5200 [4.096285e-05]
5400 [3.598915e-05]
5600 [3.166856e-05]
5800 [2.7909213e-05]
6000 [2.4631132e-05]
6200 [2.1764383e-05]
6400 [1.9254665e-05]
6600 [1.7050676e-05]
6800 [1.511747e-05]
7000 [1.3414909e-05]
7200 [1.1912405e-05]
7400 [1.0588403e-05]
7600 [9.418834e-06]
7800 [8.382822e-06]
8000 [7.4662667e-06]
8200 [6.6574676e-06]
8400 [5.933968e-06]
8600 [5.2965725e-06]
8800 [4.7268527e-06]
9000 [4.2218962e-06]
9200 [3.7727457e-06]
9400 [3.3737724e-06]
9600 [3.0182632e-06]
9800 [2.7011563e-06]


[[ 0.9979787 ]
 [-0.99998224]
 [-0.999635  ]
 [ 1.0023363 ]]

In [9]:
Tensor.randn((2, 2)).max()

0.14399215579032898

In [3]:
# Test creational ops
ones = Tensor.ones((8, 4, 2))
print(ones)
zeros = Tensor.zeros((2, 4))
print(zeros)
eye = Tensor.eye(2)
print(eye)
a_range = Tensor.arange(-5, 5, 0.25)
print(a_range)
randn = Tensor.randn((2, 3))
print(randn)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[-5.   -4.75 -4.5  -4.25 -4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25
 -2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75]
[[-0.04471869 -0.7090294  -0.8956355 ]
 [-2.4274523  -0.44212446 -0.89774364]]


In [14]:
np.mean([[1, 2, 3, 4]], 1)

array([2.5])

In [19]:
x = np.random.randn(4, 2)

In [20]:
x.size

8

In [9]:
Tensor.randn((2, 2)).mean(1)

[-0.15714246  0.9479264 ]

In [10]:
max([2, 3, 4])

4

In [ ]:
[0, 0, 1]

In [37]:
x = np.array([2, 3])

for i in range(15):
    x = x - (0.1 * global_grad)
#---------
a = 1 + x
b = a.sum()
c = b * 2

print(c)

global_grad = 2 * np.array([1, 1]) * 1

# global_grad

1.9999999999999996


In [50]:
x = np.random.randint(1, 2, (2, 2))
x = np.pad(x, 1)
x

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [70]:
pad_width = (1, 1)
mode='constant'
constant_values=0


x = np.random.randint(1, 2, (2, 2))
padded_x = np.pad(x, pad_width, mode=mode, constant_values=constant_values)

print(padded_x)

slices = tuple(slice(pad[0], -pad[1] if pad[1] > 0 else None) for pad in pad_width)
print(slices)



[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


TypeError: 'int' object is not subscriptable

In [72]:
import numpy as np

# Forward operation: Padding
pad_width = ((1, 1), (1, 1))
x = np.random.randint(1, 10, (2, 2))
padded_x = np.pad(x, pad_width, mode='constant', constant_values=0)
print("Padded Array:")
print(padded_x)

# Simulated backward operation: Removing padding from gradient
# Assuming the gradient received back is of the same shape as padded_x, filled with ones
grad_output = np.ones_like(padded_x)  # This represents the gradient passed back from the next layer
# Calculate the slice indices for extracting the gradient for the original shape
slices = tuple(slice(pad[0], -pad[1] if pad[1] > 0 else None) for pad in pad_width)
original_grad = grad_output[slices]
print("Original Gradient After Removing Padding:")
print(original_grad)

Padded Array:
[[0 0 0 0]
 [0 3 3 0]
 [0 3 7 0]
 [0 0 0 0]]
Original Gradient After Removing Padding:
[[1 1]
 [1 1]]


In [113]:

x = np.array([[1, 2], [3, 4]])
pad_width = ((1, 1), (2, 1))
x_pad = np.pad(x, pad_width)
print(x_pad)
print([(pad[0], -pad[1] if pad[1] > 0 else None) for pad in pad_width])
slices = tuple(slice(pad[0], -pad[1] if pad[1] > 0 else None) for pad in pad_width)
x_pad[slices]

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 0 3 4 0]
 [0 0 0 0 0]]
[(1, -1), (2, -1)]


array([[1, 2],
       [3, 4]])

In [115]:
print(x_pad)
x_pad[1:-1, 2:-1]

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 0 3 4 0]
 [0 0 0 0 0]]


array([[1, 2],
       [3, 4]])

In [88]:
x = np.array([[1, 2], [3, 4]])
print(x)
padded_x = np.pad(x, ((1, 1), (2, 2)), mode='constant', constant_values=0)


slices = tuple(slice(pad[0], -pad[1] if pad[1] > 0 else None) for pad in ((1, 1), (2, 2)))
padded_x[slices]

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [127]:
np.random.randint(-10)

ValueError: low >= high

In [118]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [121]:
np.random.uniform(1, 5, (1, 2))

array([[2.8674028 , 1.52473784]])

In [149]:
iterations = 1000000
loc = 1
scale = 2

gens = []
for _ in range(iterations):
    gen = np.random.normal(loc, scale)
    gens.append(gen)
    
gen_mean = np.mean(gens)
gen_std = np.std(gens)

print(f"mean: {gen_mean:.4f}, std: {gen_std:.4f}")
# np.random.normal(0, 2)

mean: 0.9968, std: 2.0019


In [135]:
# help(np.random.normal)

In [160]:
a = np.random.randn(2, 3, 4)
print(a.shape)
r = np.reshape(a, (-1, 2))
print(r.shape)

(2, 3, 4)
(12, 2)


In [158]:
r

array([ 0.45979965,  0.43619348, -0.08389548, -1.3497816 ,  2.45403294,
        0.38383975,  0.79300602,  1.87542863,  2.75826507,  1.02701674,
       -0.16676227,  0.588941  , -0.58335351,  0.25987984, -0.90546309,
       -0.27237536, -0.30579083,  1.07224693, -0.73319399,  0.95927571,
       -0.00443822, -0.45567339, -0.88115925,  0.55193867])

In [171]:
a = np.arange(1, 9, 1).reshape(1, 2, 2, 2)
print("init a")
print(a)
print(f"a shape: {a.shape}")

print("\n")
flat_a = a.reshape(-1)
print("flattened a")
print(flat_a)
print(f"flat a shape: {flat_a.shape}")


init a
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
a shape: (1, 2, 2, 2)


flattened a
[1 2 3 4 5 6 7 8]
flat a shape: (8,)


In [190]:
print(a)

a.reshape((4, -1))

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [199]:
a[:, :, 0]

array([[[1, 2],
        [5, 6]]])

In [200]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [202]:
a.view()

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [3]:
import torch
import numpy as np

In [4]:
a = np.arange(1, 9, 1).reshape(1, 2, 2, 2)
b = torch.arange(1, 9, 1).view(1, 2, 2, 2)

print(a)
print(b)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])


In [60]:
dim_0 = (-1)
dim_1 = ((1, -1))
dim_2 = ((1, -1, a.shape[2]*2))
dim_3 = (1, 1, 1, -1)
a.reshape(dim_3)

# a.reshape(-1)

array([[[[1, 2, 3, 4, 5, 6, 7, 8]]]])

In [96]:
a[-1:]

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [78]:
a[:, :, 1].reshape(-1)

array([3, 4, 7, 8])

In [87]:
print(b)

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])


In [148]:
b.flatten(2)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])

In [61]:
b.flatten?

Docstring:
flatten(start_dim=0, end_dim=-1) -> Tensor

See :func:`torch.flatten`
Type:      builtin_function_or_method

In [127]:
start = 1
end = None

a[..., ::2].reshape(-1)

array([1, 3, 5, 7])

In [131]:
print(a)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [177]:
b

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])

In [187]:
b.flatten(0, 3)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
start = 0
end = 3

if start == 0 and end == -1:
    print(a.reshape(-1))
if start == 1 and end == -1:
    print(a.reshape(1, -1))
if start == 2 and end == -1:
    print(a.reshape(1, -1, a.shape[start]*2))

# ---------------- #
if start == 0 and end == 1:
    print(a.reshape(1, -1, 2))

if start == 0 and end == 2:
    print(a.reshape(-1, 2))

if start == 0 and end == 3:
    print(a.reshape(-1))


[1 2 3 4 5 6 7 8]


In [216]:
out = []

for i in a:
    # out.append(i.reshape(-1))
    for j in i:
        out.append(j.reshape(-1))
# print(out)
np.stack(out)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [275]:
b.size()

torch.Size([1, 2, 2, 2])

In [301]:
b.flatten(2)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])

In [283]:
len(a.shape)

4

In [302]:
def flat(x, start, end=-1):
    if end >= len(x.shape) or start >= len(x.shape):
        return

    if end == -1:
        end = len(x.shape) - 1
    
    def flatten(array, dim, start, stop):
        out = []
        for items in array:
            if dim < start:
                print("rec")
                return flatten(items, dim+1, start, stop)
            elif dim == stop + 1:
                return np.stack(out)
            else:
                out.append(items.reshape(-1))
        if len(out) == 1:
            return out[0]
        else:
            return np.stack(out)
        
    return flatten(x, 0, start, end)
                

In [307]:
flat(a, 1)

rec


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [310]:
a.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [266]:
a[..., 1]

array([[[2, 4],
        [6, 8]]])

In [314]:
for ar in a:
    for i in ar:
        print("hi")

hi
hi


In [320]:

def np_flatten(x, start_dim, end_dim=-1):
    # Check if end_dim is -1, which implies flattening to the last dimension
    if end_dim == -1:
        end_dim = len(x.shape) - 1
    
    # Dimensions before the flattening
    shape_before = x.shape[:start_dim]
    
    # Dimensions to flatten, from start_dim to end_dim
    flatten_shape = np.prod(x.shape[start_dim:end_dim + 1])
    
    # Dimensions after the flattening
    shape_after = x.shape[end_dim + 1:]
    
    # New shape combining all parts
    new_shape = shape_before + (flatten_shape,) + shape_after
    
    # Reshape the array
    return x.reshape(new_shape)


np_flatten(a, 1, 2)

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [333]:
x = a
start_dim = 1
end_dim = 3

    # Dimensions before the flattening
shape_before = x.shape[:start_dim]
    
    # Dimensions to flatten, from start_dim to end_dim
flatten_shape = np.prod(x.shape[start_dim:end_dim + 1])
shape_after = x.shape[end_dim + 1:]


shape_before + (flatten_shape, ) + shape_after

(1, 8)

In [327]:
np.prod(x.shape[1:2+1])

4

In [334]:
x.shape[:start_dim]

(1,)

In [335]:
(2, ) + () + (1, ) + (1, )

(2, 1, 1)

In [ ]:
def np_flatten(x, start_dim, end_dim=-1):
    new_shape = (x.shape[:start_dim] + 
                 (np.prod(x.shape[start_dim:end_dim + 1 if end_dim != -1 else None]),) +
                 x.shape[end_dim + 1 if end_dim != -1 else None:])
    return x.reshape(new_shape)

In [ ]:
np.prod(

In [321]:
np.prod??

Signature:      
np.prod(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.prod(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function prod at 0x7fb3ecc7cca0>
File:            ~/opt/anaconda3/envs/ptb/lib/python3.10/site-packages/numpy/core/fromnumeric.py
Source:         
@array_function_dispatch(_prod_dispatcher)
def prod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue,
         initial=np._NoValue, where=np._NoValue):
    """
    Return the product of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a product is performed.  The default,
        axis=None, will calculate the product of all the elements in the
        input array. If axis is negative it counts from the last to the
        first axis.

        .. vers

In [337]:
val = np.random.randn(1, 2, 2, 2)

In [339]:
val.reshape()

array([ 0.84192192, -1.36975739, -1.77335081,  0.74715344,  0.07809733,
       -0.38122494,  0.86518989,  0.40399694])

In [340]:
tval = torch.randn(1, 2, 2, 2)

tensor([[[[-0.4883,  0.0058],
          [ 0.0032, -0.5770]],

         [[-1.0523,  0.7121],
          [-0.6822,  0.3962]]]])

In [353]:
tval.size()

torch.Size([1, 2, 2, 2])

In [371]:
tval.flatten(0)

tensor([-0.4883,  0.0058,  0.0032, -0.5770, -1.0523,  0.7121, -0.6822,  0.3962])

In [ ]:
[[[1, 2], 
 [3, 4]]]

In [ ]:
(1, 2, 2)

In [ ]:
[[[1, 2], 
 [3, 4]]]

In [373]:
x = np.random.randn(1, 2, 2, 4)
# x.reshape(-1)

In [399]:
start = 1
end = 2

start_shape = x.shape[:start]
print(f"start shape: {start_shape}")

flat_shape = (np.prod(x.shape[start:end + 1]), )
print(f"flat shape: {flat_shape}")

end_shape = x.shape[end+1:]
print(f"end shape: {end_shape}")


# This
shape = start_shape + flat_shape + end_shape
print(shape)
x.reshape(shape)

start shape: (1,)
flat shape: (4,)
end shape: (4,)
(1, 4, 4)


array([[[-0.81649415,  1.34022568, -0.09791535,  0.09763588],
        [-0.24621646, -1.2966878 ,  0.6383912 , -1.53588527],
        [-0.00186106,  0.95540583,  1.15952254,  0.54602754],
        [-0.07452992,  0.99371103,  0.34019836,  0.86773557]]])

In [394]:
my_tup = (2, ) + (3, )
my_tup

(2, 3)

In [392]:
(2, ) + (3, )

(2, 3)

In [386]:
np.array([[2, 2, 2], 
          [2, 2, 2]]).shape

(2, 3)

In [389]:
np.random.randn(16, 16).reshape(16 * 16).shape

(256,)