In [1]:
from engine import Tensor
import numpy as np
import nn

In [9]:
## Does it work in simple contexts?

xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [[1.0], 
      [-1.0], 
      [-1.0], 
      [1.0]]


net = nn.MLP()

x = Tensor(xs)
y_real = Tensor(ys)

for k in range(10000):
    net.zero_grad()
    y_pred = net(x)
#     loss = ((y_pred - y_real)**2).sum() / y_real.shape[0]
    loss = ((y_pred - y_real)**2).mean(0)
#     loss = loss_fn(y_pred, y_real)
    loss.backward()
    
    for p in net.parameters():
        if p.grad is not None:
            p.data -= 0.005 * p.grad  # Apply the learning rate.
    
    if k % 200 == 0:
        print(k, loss.data)
    
y_pred

0 [0.98269457]
200 [0.1302591]
400 [0.00475212]
600 [0.00140133]
800 [0.0003008]
1000 [4.5727225e-05]
1200 [6.080242e-06]
1400 [7.7118284e-07]
1600 [9.62288e-08]
1800 [1.20045875e-08]
2000 [1.559382e-09]
2200 [2.556746e-10]
2400 [7.108625e-11]
2600 [1.5167423e-11]
2800 [1.2093437e-11]
3000 [1.0513368e-11]
3200 [1.01225694e-11]
3400 [9.869439e-12]
3600 [8.6295415e-12]
3800 [7.657874e-12]
4000 [7.979395e-12]
4200 [7.990053e-12]
4400 [7.319478e-12]
4600 [6.924239e-12]
4800 [6.3593575e-12]
5000 [6.6444628e-12]
5200 [6.924239e-12]
5400 [6.735945e-12]
5600 [6.083134e-12]
5800 [6.093792e-12]
6000 [6.083134e-12]
6200 [5.5537797e-12]
6400 [5.635492e-12]
6600 [5.0599525e-12]
6800 [5.4889426e-12]
7000 [5.3725913e-12]
7200 [5.3725913e-12]
7400 [5.3725913e-12]
7600 [5.3725913e-12]
7800 [5.3725913e-12]
8000 [5.3725913e-12]
8200 [5.3725913e-12]
8400 [5.3725913e-12]
8600 [5.3725913e-12]
8800 [5.3725913e-12]
9000 [5.3725913e-12]
9200 [5.3725913e-12]
9400 [5.3725913e-12]
9600 [5.3725913e-12]
9800 [5.372

[[ 1.0000006 ]
 [-0.9999976 ]
 [-1.000003  ]
 [ 0.99999744]]

In [7]:
Tensor.randn((2, 2)).max()

1.0734491348266602

In [3]:
# Test creational ops
ones = Tensor.ones((8, 4, 2))
print(ones)
zeros = Tensor.zeros((2, 4))
print(zeros)
eye = Tensor.eye(2)
print(eye)
a_range = Tensor.arange(-5, 5, 0.25)
print(a_range)
randn = Tensor.randn((2, 3))
print(randn)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[-5.   -4.75 -4.5  -4.25 -4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25
 -2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75]
[[-0.04471869 -0.7090294  -0.8956355 ]
 [-2.4274523  -0.44212446 -0.89774364]]


In [14]:
np.mean([[1, 2, 3, 4]], 1)

array([2.5])

In [19]:
x = np.random.randn(4, 2)

In [20]:
x.size

8

In [9]:
Tensor.randn((2, 2)).mean(1)

[-0.15714246  0.9479264 ]