In [1]:
from engine import Tensor
import numpy as np
import nn

In [2]:
## Does it work in simple contexts?

xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [[1.0], 
      [-1.0], 
      [-1.0], 
      [1.0]]


net = nn.MLP()

x = Tensor(xs)
y_real = Tensor(ys)

for k in range(10000):
    net.zero_grad()
    y_pred = net(x)
    loss = ((y_pred - y_real)**2).sum() / y_real.shape[0]
#     loss = loss_fn(y_pred, y_real)
    loss.backward()
    
    for p in net.parameters():
        if p.grad is not None:
            p.data -= 0.005 * p.grad  # Apply the learning rate.
    
    if k % 200 == 0:
        print(k, loss.data)
    
y_pred

0 1.9549365
200 0.026121212
400 0.0064662243
600 0.0016118803
800 0.0003952924
1000 0.000109482804
1200 4.5122797e-05
1400 3.0809453e-05
1600 2.7496322e-05
1800 2.6570564e-05
2000 2.6159656e-05
2200 2.5860216e-05
2400 2.5588426e-05
2600 2.5322435e-05
2800 2.5058165e-05
3000 2.4798272e-05
3200 2.4540645e-05
3400 2.4283552e-05
3600 2.4034085e-05
3800 2.3785069e-05
4000 2.3539098e-05
4200 2.3295433e-05
4400 2.3053817e-05
4600 2.2814796e-05
4800 2.2577753e-05
5000 2.2341339e-05
5200 2.2106935e-05
5400 2.1873966e-05
5600 2.1642245e-05
5800 2.1412154e-05
6000 2.1183429e-05
6200 2.0955424e-05
6400 2.073e-05
6600 2.0505251e-05
6800 2.028741e-05
7000 2.0070329e-05
7200 1.9854811e-05
7400 1.9643292e-05
7600 1.9431765e-05
7800 1.9221749e-05
8000 1.9012976e-05
8200 1.8807492e-05
8400 1.860299e-05
8600 1.8401039e-05
8800 1.8200557e-05
9000 1.8001487e-05
9200 1.7803863e-05
9400 1.7607028e-05
9600 1.741232e-05
9800 1.7218372e-05


[[ 1.0057478]
 [-1.000001 ]
 [-1.0000929]
 [ 0.9940784]]

In [3]:
# Test creational ops
ones = Tensor.ones((8, 4, 2))
print(ones)
zeros = Tensor.zeros((2, 4))
print(zeros)
eye = Tensor.eye(2)
print(eye)
a_range = Tensor.arange(-5, 5, 0.25)
print(a_range)
randn = Tensor.randn((2, 3))
print(randn)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[-5.   -4.75 -4.5  -4.25 -4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25
 -2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75]
[[-0.04471869 -0.7090294  -0.8956355 ]
 [-2.4274523  -0.44212446 -0.89774364]]
