In [1]:
from engine import Tensor
import numpy as np
import nn

In [7]:
net = nn.MLP()

In [3]:
net = nn.MLP()

xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [[1.0], [-1.0], [-1.0], [1.0]]

y_hat = net(Tensor(xs))
y_real = Tensor(ys)

In [7]:
y_hat

[[0.        ]
 [0.16429852]
 [0.        ]
 [0.        ]]

In [4]:
y_real.shape[0]

4

In [11]:
# from numba import jit

# @jit(nopython=True)
# def loss_fn(y_hat, y_real):
#     loss = ((y_hat - y_real)**2).sum() / y_real.shape[0]
#     return loss

In [25]:
xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [[1.0], 
      [-1.0], 
      [-1.0], 
      [1.0]]


net = nn.MLP()

x = Tensor(xs)
y_real = Tensor(ys)

for k in range(10000):
    net.zero_grad()  # Use the zero_grad method to properly zero out gradients.
    y_pred = net(x)
    loss = ((y_pred - y_real)**2).sum() / y_real.shape[0]
#     loss = loss_fn(y_pred, y_real)
    loss.backward()
    
    for p in net.parameters():
        if p.grad is not None:
            p.data -= 0.005 * p.grad  # Apply the learning rate.
    
    if k % 200 == 0:
        print(k, loss.data)
    
y_pred

0 1.6143259
200 0.1426598
400 0.0062944293
600 0.0005949866
800 0.00014812025
1000 5.059447e-05
1200 1.8746636e-05
1400 7.2093917e-06
1600 2.8343127e-06
1800 1.1295688e-06
2000 4.5412784e-07
2200 1.8339904e-07
2400 7.451002e-08
2600 3.0498935e-08
2800 1.2621408e-08
3000 5.1890323e-09
3200 2.144045e-09
3400 1.037038e-09
3600 5.4879923e-10
3800 3.51136e-10
4000 2.5344793e-10
4200 1.8632562e-10
4400 1.7123458e-10
4600 1.5911628e-10
4800 1.5126478e-10
5000 1.4310686e-10
5200 1.3323387e-10
5400 1.2490275e-10
5600 1.1798562e-10
5800 1.1335288e-10
6000 1.0630252e-10
6200 1.01000985e-10
6400 9.64544e-11
6600 9.329515e-11
6800 8.602541e-11
7000 8.1400664e-11
7200 7.76712e-11
7400 7.45537e-11
7600 7.224177e-11
7800 6.827605e-11
8000 6.636913e-11
8200 6.445777e-11
8400 6.2155614e-11
8600 6.1360694e-11
8800 6.0044414e-11
9000 5.853984e-11
9200 5.82725e-11
9400 5.6400218e-11
9600 5.411227e-11
9800 5.3632654e-11


[[ 1.0000103]
 [-0.9999937]
 [-1.0000002]
 [ 0.999992 ]]

In [6]:
for p in net.parameters():
    print(p.grad)

[[ 0.10926643  0.34880325  0.34553602  0.00214646]
 [-0.03642214 -0.02780569 -0.02754523 -0.00071549]
 [ 0.01821107  0.12763979  0.12644419  0.00035774]]
[[0. 0. 0. 0.]]
[[0.         0.00267239 0.         0.        ]
 [0.         0.18684575 0.         0.        ]
 [0.         0.6182679  0.         0.        ]
 [0.         0.38165408 0.         0.        ]]
[[0. 0. 0. 0.]]
[[0.       ]
 [4.3699355]
 [0.       ]
 [0.       ]]
[[0.]]


In [14]:
z = np.random.randn(4, 4)@np.random.randn(4, 1) + np.zeros((1, 1))
z.shape

(4, 1)

In [16]:
c = np.zeros((1, 1))
c += np.random.randn(4, 1)

ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (4,1)

In [8]:
loss.backward()

[1.]
[[1.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 [0.]]
(4, 1)
[[-2.]
 [ 2.]
 [ 2.]
 [-2.]]
None
None
None
[[-2.]
 [ 2.]
 [ 2.]
 [-2.]]
[[-0.6084045 ]
 [-0.9584013 ]
 [-0.06329735]
 [-1.1529789 ]]
(4, 1)
[0.]
(1,)


ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (4,1)

In [34]:
to_reduce.shape

(4, 1)

In [43]:
np.expand_dims([1, 1], 0)

array([[1, 1]])

In [ ]:
# Broadcasting rules

In [72]:
b = np.random.randn(1, 4, 2) # match the input dims and you are good.
c = np.random.randn(4, 2)

(b * c).shape

(1, 4, 2)

In [73]:
a = np.random.randn(1, 4, 2)

a += (b * c)
a.shape

(1, 4, 2)

In [54]:

# c.shape

In [71]:
np.random.randn(1, 4, 2).sum(0).shape

(4, 2)

In [40]:
to_reduce = np.random.randn(4, 1)
grad = np.ones_like(to_reduce)
# to_reduce.sum(0)
grad

array([[1.],
       [1.],
       [1.],
       [1.]])

To fix sum you just need to match the shape of the self.data coming in, I think. More accuratly you need to match the shape of the transformation maybe: idk. Need to work with sum more. numpy and torch has sum play with them.


Need to get the dims to match correctly, this will take some experimentation: and deep thought. 

Foundationaly need to understand reduction ops. This is what is hard for me I think


What do I know
- Its still add so der = 1
- Its shape needs to broadcast in the der, so if the shape is 4, 1 on the input

In [14]:
a = np.random.randn(4, 1)
b = np.random.randn(4, 1)
a + b

array([[ 0.97902001],
       [-2.22508662],
       [-1.67047627],
       [-0.2965853 ]])

In [16]:
for p in net.parameters():
    print(p.requires_grad)

True
True
True
True
True
True


In [7]:
y_real

[[ 1.]
 [-1.]
 [-1.]
 [ 1.]]

In [12]:
for i in loss._prev:
    print(i)

{2, [[-1.]
 [ 1.]
 [ 1.]
 [-1.]]}


In [8]:
loss.backward()

[4.07063]
[[1.       ]
 [1.       ]
 [1.0730093]
 [0.9976208]]
[[-1.       ]
 [ 1.       ]
 [ 1.0358616]
 [-0.9988097]]
[[0.        ]
 [0.        ]
 [0.03586162]
 [0.00119028]]
[[ 0.0000000e+00]
 [-1.6198169e+00]
 [ 3.5861615e-02]
 [ 1.1902830e-03]]
[[0.]]
[[ 0.0000000e+00]
 [-1.6198169e+00]
 [ 3.5861615e-02]
 [ 1.1902830e-03]]
[[0.         0.         0.         0.        ]
 [0.         2.420442   0.         0.        ]
 [0.         0.         0.3001468  0.        ]
 [0.         0.         0.00996217 0.        ]]
[[ 0.          0.          0.          0.        ]
 [-2.5953069   2.420442   -3.161884   -0.6409065 ]
 [-0.43346208 -0.06011634  0.3001468  -0.15714166]
 [-0.28839874 -0.12067308  0.00996217 -0.29038864]]
[[ 0.          0.          0.          0.        ]
 [-2.5953069   2.420442   -3.161884   -0.6409065 ]
 [-0.43346208 -0.06011634  0.3001468  -0.15714166]
 [-0.28839874 -0.12067308  0.00996217 -0.29038864]]
[[0.         0.         0.         0.        ]
 [0.         0.         

ValueError: cannot reshape array of size 4 into shape (1,)

In [13]:
type(loss)

engine.Tensor

In [4]:
net.parameters()

<generator object Module.parameters at 0x7fba2f775eb0>

In [3]:
net.zero_grad()

In [4]:
for param in net.parameters():
    if param.requires_grad:
#         param.data -= self.lr * param.grad
        print(param)

[[-0.1243251  -0.9172921   1.182684   -1.0130153 ]
 [ 0.0288723   1.3303456  -0.11303287  0.24445443]
 [-1.1465033   0.86183876  0.4577391  -0.36788297]]
[[0. 0. 0. 0.]]
[[ 0.28105614 -0.3855348   0.7029505   0.34809703]
 [-0.41025335 -0.5370706  -1.1471525  -0.20046443]
 [-0.37782416  0.5260139  -0.13071114  0.3492137 ]
 [-1.03824    -0.7071723  -0.5668519   0.07607934]]
[[0. 0. 0. 0.]]
[[ 1.0335304 ]
 [-0.10125775]
 [ 0.24842171]
 [ 0.9971799 ]]
[[0.]]


In [6]:
x = Tensor([[1, 2]])
print(x.shape)
l1(x).shape

(1, 2)


(1, 3)

In [15]:
for p in net.parameters().values():
    print(p.parameters())

{'w': [[ 0.95477086  0.8455835   0.98341113  0.7739111 ]
 [ 0.9920584   0.34109655 -0.22134824  1.0318031 ]
 [ 1.3880258  -0.6933539  -0.00778713  0.9643549 ]], 'b': [0. 0. 0. 0.]}
{'w': [[-1.018422    0.16992508 -0.06235736  0.9246361 ]
 [-1.1396269   0.2504219  -0.78362983 -0.10598446]
 [-1.130974    0.29714298 -0.39758295  0.66354245]
 [ 1.2067316   1.0690259   0.1981175   0.08408989]], 'b': [0. 0. 0. 0.]}
{'w': [[ 0.07227279]
 [-0.25291726]
 [-0.7082981 ]
 [ 0.64171904]], 'b': [0.]}


In [3]:
l1 = nn.Linear(2, 3)

In [11]:
vars(l1)

{'w': [[-0.5850506   1.6288409   0.39408326]
  [ 1.1982913  -1.0406932  -0.23052394]],
 'b': [0. 0. 0.]}

In [7]:
x1 = Tensor([[4.0, 2.0]], requires_grad=True)
w1 = Tensor([[3.0, 4.0]], requires_grad=True)



b1 = Tensor([[7.0]], requires_grad=True)

In [ ]:
xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1.0, -1.0],
]

ys = [1.0, -1.0, -1.0, 1.0]

In [10]:
x1.shape

(1, 2)

In [7]:
test = np.array([2, 3], np.float32)

In [14]:
input_1 = [[1, 2]]
input_2 = np.array([[1, 2]])

Tensor(input_1) is Tensor(input_2)

False

In [20]:
Tensor.kaiming_uniform(3, 2).shape

(3, 2)

In [3]:
import numpy as np

In [7]:
np.random.normal(0, 1, (3, 3))

array([[-0.56948177,  1.47046888, -0.70346975],
       [-2.12550729,  1.64349633, -0.18920115],
       [ 0.06239465,  0.3143566 ,  0.88756801]])

In [ ]:
def kaiming_uniform(fan_in, fan_out):
    limit = np.sqrt(6 / fan_in)
    return np.random.uniform(-limit, limit, (fan_out, fan_in))

In [22]:
# Model init
def xavier_init(shape: tuple):
    in_dims, out_dims = shape
    variance = 2 / (in_dims + out_dims)
    return np.random.normal(0, np.sqrt(variance), shape)


def init_layer(n_in, n_out):
    w = np.random.normal(0, 1, (n_in, n_out))
    b = np.random.normal(0, 1, (n_out))
    return Tensor(w, requires_grad=True), Tensor(b, requires_grad=True)

In [23]:
x = Tensor(np.random.normal(0, 1, (1, 3)), requires_grad=True)

w, b = init_layer(3, 4)

x@w + b

[[-1.2053158  2.538495  -1.2465813  2.213791 ]]

In [24]:
w@x

AssertionError: (3, 4), (1, 3): Incompatible shapes for matrix multiplication.

In [14]:
def access_params(net_params, func):
    for layers in net_params.values():
        for p in layers.parameters().values():
            func(p)
        
def zero_grad(params):
    for p in params.data:
        print(p)
        p = np.zeros_like(p)
        print(p)
        
def print_params(params):
    print(params)

In [15]:
access_params(net.parameters(), print_params)

[[-0.86006254 -0.30643904 -0.21797846  1.0343217 ]
 [-1.1683605   0.95028704 -0.40874273  0.4400779 ]
 [-0.14941764  0.5234418   0.82390934  0.97237396]]
[[0. 0. 0. 0.]]
[[ 1.0939686   0.61001337 -0.64165026  0.71326745]
 [-0.3159256  -0.44704282  1.1607931  -0.32719943]
 [-0.76023024  1.1756271  -0.33649942 -1.1185616 ]
 [ 0.74409056 -0.86787856 -0.07981426  0.07215461]]
[[0. 0. 0. 0.]]
[[ 0.83443314]
 [-0.18828385]
 [-0.06012312]
 [-0.46142915]]
[[0.]]


In [16]:



access_params(net.parameters(), zero_grad)

[-0.86006254 -0.30643904 -0.21797846  1.0343217 ]
[0. 0. 0. 0.]
[-1.1683605   0.95028704 -0.40874273  0.4400779 ]
[0. 0. 0. 0.]
[-0.14941764  0.5234418   0.82390934  0.97237396]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 1.0939686   0.61001337 -0.64165026  0.71326745]
[0. 0. 0. 0.]
[-0.3159256  -0.44704282  1.1607931  -0.32719943]
[0. 0. 0. 0.]
[-0.76023024  1.1756271  -0.33649942 -1.1185616 ]
[0. 0. 0. 0.]
[ 0.74409056 -0.86787856 -0.07981426  0.07215461]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0.83443314]
[0.]
[-0.18828385]
[0.]
[-0.06012312]
[0.]
[-0.46142915]
[0.]
[0.]
[0.]


In [ ]:
for k in range(10000):
    ypred = [n(x) for x in xs]
    loss = sum([(y_hat - y_real)**2 for y_real, y_hat in zip(ys, ypred)])
    
    
    for p in n.parameters():
        p.grad = 0 # zero grad
    loss.backward()
    
    for p in n.parameters():
        p.data += -0.05 * p.grad
    print(k, loss.data)
ypred

In [4]:
net = nn.MLP()

AttributeError: type object 'Tensor' has no attribute 'zero_init'

In [13]:
class Test:
    def __init__(self):
        self.a1 = 'hi'
        self.a2 = 'hihi'
        
    def parameters(self):
        return vars(self).

In [14]:
t = Test()

In [16]:
var_dict = t.parameters()

In [ ]:
var_dict

In [29]:
class Kwa:
    def __init__(self, name="None"):
        self.name = name
    
    @classmethod
    def make(cls, **kwargs):
        return cls(**kwargs)
    
    def __repr__(self):
        return f"KWA({self.name})"

In [30]:
k = Kwa.make(name="Cam")

In [32]:
k.name

'Cam'

In [25]:
self_tensor = np.random.randn(4, 1)
other_tensor = np.random.randn(1, 1)

grad_tensor = np.random.randn(1, 1)


grad_self_shape = np.broadcast_to(other_tensor, self_tensor.shape).shape
grad_self_shape

(4, 1)

In [29]:
grad_tensor += np.sum(self_tensor, axis=tuple(i for i in range(self_tensor.ndim) if grad_self_shape[i] == 1), keepdims=True)

ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (4,1)

In [23]:
np.broadcast_to??

In [19]:
data = np.random.randn(1, 1)
print(data)



print(np.sum(data))

[[-0.42807348]]
-0.4280734824847532


In [13]:
np.random.randn(*(1, 2))

array([[-1.4321468, -0.5955731]])

In [21]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [24]:
210e-6

0.00021